### ISSUE TITLE
Error transforming /project/file.js with 'babel' plugin: It looks like your Babel configuration specifies a module transformer. Please disable it.

### ISSUE THREAD

**Issue by btakita** [rollup/rollup-plugin-babel#114]
I'm getting the following...

```
Error transforming /project/file.js with 'babel' plugin: It looks like your Babel configuration specifies a module transformer. Please disable it. See https://github.com/rollup/rollup-plugin-babel#configuring-babel for more information
Error: Error transforming /project/file.js with 'babel' plugin: It looks like your Babel configuration specifies a module transformer. Please disable it. See https://github.com/rollup/rollup-plugin-babel#configuring-babel for more information
    at preflightCheck (/project/node_modules/rollup-plugin-babel/dist/rollup-plugin-babel.cjs.js:48:104)
    at Object.transform$1 [as transform] (/project/node_modules/rollup-plugin-babel/dist/rollup-plugin-babel.cjs.js:119:18)
    at /project/node_modules/rollup/src/utils/transform.js:19:35
    at process._tickCallback (node.js:382:9)
    at Function.Module.runMain (module.js:433:11)
    at startup (node.js:141:18)
    at node.js:977:3
```

Here is the transformed js being sent to the `preflightCheck`.

```
"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

var Foo = function Foo() {
  _classCallCheck(this, Foo);
};

exports.default = Foo;
```

Here are my dependencies in `package.json`

```
{
    "atob-lite": "^1.0.0",
    "aws-sdk": "2.7.16",
    "babel-cli": "^6.18.0",
    "babel-core": "^6.21.0",
    "babel-plugin-external-helpers": "^6.18.0",
    "babel-plugin-transform-es2015-modules-commonjs": "6.18.0",
    "babel-plugin-transform-regenerator": "^6.21.0",
    "babel-polyfill": "^6.20.0",
    "babel-preset-es2015": "6.18.0",
    "babel-preset-es2015-loose-rollup": "^7.0.0",
    "babel-preset-es2015-riot": "^1.1.0",
    "babel-preset-es2015-rollup": "^3.0.0",
    "babel-preset-node6": "^11.0.0",
    "babel-preset-stage-2": "^6.18.0",
    "babel-register": "^6.18.0",
    "babel-runtime": "^6.20.0",
    "babel-traverse": "6.21.0",
    "babel-types": "6.21.0",
    "body-parser": "^1.15.2",
    "bourbon": "^4.2.7",
    "btoa-lite": "^1.0.0",
    "cli": "^1.0.1",
    "co": "^4.6.0",
    "co-fs": "^1.2.0",
    "csv": "^1.1.0",
    "deep-equal": "^1.0.1",
    "dotenv": "^2.0.0",
    "escape-html": "^1.0.3",
    "fast-csv": "^2.3.0",
    "fs-extra": "^1.0.0",
    "fs-promise": "^1.0.0",
    "graceful-fs": "^4.1.11",
    "gzip-size": "^3.0.0",
    "inquirer": "^2.0.0",
    "inquirer-autocomplete-prompt": "github:vweevers/inquirer-autocomplete-prompt#inquirer-0.11",
    "isomorphic-fetch": "^2.2.1",
    "js-console-color": "^0.2.0",
    "jsdoc": "^3.4.3",
    "json-loader": "^0.5.4",
    "koa": "^1.2.4",
    "koa-basic-auth": "^1.1.2",
    "koa-bodyparser": "^2.3.0",
    "koa-cors": "0.0.16",
    "koa-passport": "^1.3.1",
    "koa-redirects": "^1.1.0",
    "koa-route": "^2.4.2",
    "koa-sendfile": "^2.0.0",
    "koa-sslify": "^1.1.0",
    "koa-static": "^2.0.0",
    "mailchimp-api": "^2.0.7",
    "minami": "^1.1.1",
    "minimist": "^1.2.0",
    "mz": "^2.6.0",
    "newrelic": "^1.35.1",
    "node-resolve": "^1.3.3",
    "node-sass": "^4.1.1",
    "nodemon": "1.11.0",
    "papaparse": "^4.1.2",
    "parseUri": "^1.2.3-2",
    "passport": "^0.3.2",
    "passport-http-bearer": "^1.0.1",
    "passport-oauth": "^1.0.0",
    "pg": "^6.1.2",
    "pg-native": "^1.10.0",
    "pg.js": "^4.1.1",
    "pug": "^2.0.0-beta6",
    "pug-cli": "^1.0.0-alpha6",
    "ramda": "^0.22.1",
    "riot": "3.0.5",
    "riot-compiler": "3.1.1",
    "riot-route": "^3.0.2",
    "rocambole": "^0.7.0",
    "rocambole-strip-alert": "^1.0.0",
    "rocambole-strip-console": "^1.0.0",
    "rocambole-strip-debugger": "^1.0.0",
    "rollup": "0.37.0",
    "rollup-plugin-alias": "^1.2.0",
    "rollup-plugin-babel": "^2.7.1",
    "rollup-plugin-commonjs": "^6.0.0",
    "rollup-plugin-includepaths": "^0.2.1",
    "rollup-plugin-json": "^2.1.0",
    "rollup-plugin-node-builtins": "^2.0.0",
    "rollup-plugin-node-resolve": "^2.0.0",
    "rollup-plugin-replace": "^1.1.1",
    "rollup-plugin-riot": "^1.1.0",
    "rollup-plugin-sourcemaps": "^0.4.1",
    "rollup-plugin-uglify": "^1.0.1",
    "rollup-watch": "^2.5.0",
    "shelljs": "^0.7.5",
    "shortid": "2.2.6",
    "tag-loader": "^0.3.0",
    "text-table": "^0.2.0",
    "throng": "^4.0.0",
    "uglify-js": "^2.7.5",
    "vorpal": "^1.11.4",
    "vorpal-use": "^1.0.1",
    "whatwg-fetch": "^2.0.1"
  }
```

**Comment by btakita** [comment]
This .babelrc does not work

```
{
  "presets": ["es2015"]
}
```

This .babelrc does work

```
{
  "presets": ["babel-preset-es2015-loose-rollup"],
  "plugins": [
    "external-helpers"
  ]
}
```
