### ISSUE TITLE
plugin fails babel foreign.modules check

### ISSUE THREAD

**Issue by robhicks** [rollup/rollup-plugin-babel#127]
I'm new to rollup. I'm attempting to use the plugin to transpile es2015 code for a v1 native web components seed I'm developing. I have followed the instructions but get an error when trying to bundle.  The error is:

```bash
Error: [BABEL] /.../nwc-v1-seed/src/x.js: Using removed Babel 5 option: foreign.modules - Use the corresponding module transform plugin in the `plugins` option. Check out http://babeljs.io/docs/plugins/#modules
    at error (/.../nwc-v1-seed/node_modules/rollup/dist/rollup.js:170:12)
    at /.../nwc-v1-seed/node_modules/rollup/dist/rollup.js:8926:6
```
I'm using gulp to build. The gulpfile.js file (as well as the rest of the seed) can be found [here](https://github.com/robhicks/nwc-v1-seed). 

Any help would be appreciated.

**Comment by SpaceK33z** [comment]
This is a dupe of #120.
