### ISSUE TITLE
Cannot find module 'babel-core' (v3.0.1)

### ISSUE THREAD

**Issue by mahish** [rollup/rollup-plugin-babel#157]
Hey,
when I update the rollup-plugin-babel package to version 3 I start keep getting this error:
````
module.js:487
    throw err;
    ^

Error: Cannot find module 'babel-core'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/jiri/Documents/web-dev-server/project/node_modules/rollup-plugin-babel/dist/rollup-plugin-babel.cjs.js:4:17)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
````

I use `rollup@0.47.4`, `npm@5.3.0`, `gulp@3.9.1` in my project.

* .babelrc
````json
{
  "presets": [
    [
      "es2015",
      {
        "modules": false
      }
    ]
  ],
  "plugins": [
    "external-helpers"
  ],
  "sourceMaps": true
}
````

* gulp task:
````javascript
gulp.task('js', () => {
  return rollup(config.rollup.bundle)
    .then((bundle) => {
      bundle.write(config.rollup.output);
    });
});
````
where babel plugin has only this settings: `exclude: 'node_modules/**'`

**Comment by mahish** [comment]
Ok, I missed the information in terminal: `rollup-plugin-babel@3.0.1 requires a peer of babel-core@6 || 7 || ^7.0.0-alpha || ^7.0.0-beta || ^7.0.0-rc but none was installed.` Should be noted also in documentation and release notes. Cant see it in neither place.

**Comment by mahish** [comment]
@zzfScarecrow `npm i -D babel-core` I suppose :)
