### ISSUE TITLE
Unexpected situation arose using prop-types

### ISSUE THREAD

**Issue by jkinzel-r7** [rollup/rollup-plugin-babel#173]
I'm new to Rollup in general and I'm trying to create a re-usable/sharable React component. When I run `rollup -c` I'm getting the following error: 

```
[!] (babel plugin) Error: An unexpected situation arose. Please raise an issue at https://github.com/rollup/rollup-plugin-babel/issues. Thanks!
node_modules/prop-types/index.js
Error: An unexpected situation arose. Please raise an issue at https://github.com/rollup/rollup-plugin-babel/issues. Thanks!
    at error (/Users/***/dir/ui-component-accordion/node_modules/rollup/dist/rollup.js:185:14)
    at Object.error (/Users/**/dir/ui-component-accordion/node_modules/rollup/dist/rollup.js:9407:6)
    at promise.then.previous (/Users/**/dir/ui-component-accordion/node_modules/rollup/dist/rollup.js:9416:32)
    at <anonymous>
```

Here is my rollup config: 
```
import * as path from 'path';
import babel from 'rollup-plugin-babel';
import commonjs from 'rollup-plugin-commonjs';
import eslint from 'rollup-plugin-eslint';
import globals from 'rollup-plugin-node-globals';
import progress from 'rollup-plugin-progress';
import resolve from 'rollup-plugin-node-resolve';
import replace from 'rollup-plugin-replace';
import scss from 'rollup-plugin-scss';
import copy from 'rollup-plugin-copy';
import livereload from 'rollup-plugin-livereload';
import serve from 'rollup-plugin-serve';
import uglify from 'rollup-plugin-uglify';


const env = process.env.NODE_ENV;
const isProd = env.toLowerCase() === 'production';
const config = {
  external: ['react', 'react-dom'],
  input: 'src/index.js',
  name: 'ui-component-accordion',
  output: {
    file: isProd ? 'dist/accordion.js' : 'dev/accordion.js',
    format: isProd ? 'umd' : 'iife'
  },
  watch: {
    chokidar: true
  },
  plugins: [
    progress(),
    resolve(),
    replace({'process.env.NODE_ENV': JSON.stringify(env)}),
    commonjs({
      sourceMap: false
    }),
    scss({
      includePaths: [
        path.resolve(__dirname, 'node_modules', 'foundation-sites', 'scss')
      ],
      output: isProd ? 'dist/bundle.css' : 'dev/bundle.css'
    }),
    eslint({
      exclude: 'node_modules/**'
    }),
    babel(),
    globals()
  ].concat(isProd ? [uglify()] :[
    copy({
      'dist/bundle.css': 'dev/bundle.css'
    }),
    serve({
      contentBase: 'dev',
      open: true,
      port: 8090
    }),
    livereload('dist')
  ])
};

export default config;
```

And just for completeness here is `index.js` of `prop-types`:

```
/**
 * Copyright (c) 2013-present, Facebook, Inc.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

if (process.env.NODE_ENV !== 'production') {
  var REACT_ELEMENT_TYPE = (typeof Symbol === 'function' &&
    Symbol.for &&
    Symbol.for('react.element')) ||
    0xeac7;

  var isValidElement = function(object) {
    return typeof object === 'object' &&
      object !== null &&
      object.$$typeof === REACT_ELEMENT_TYPE;
  };

  // By explicitly using `prop-types` you are opting into new development behavior.
  // http://fb.me/prop-types-in-prod
  var throwOnDirectAccess = true;
  module.exports = require('./factoryWithTypeCheckers')(isValidElement, throwOnDirectAccess);
} else {
  // By explicitly using `prop-types` you are opting into new production behavior.
  // http://fb.me/prop-types-in-prod
  module.exports = require('./factoryWithThrowingShims')();
}
```

I am using React/React DOM v16.

**Comment by Andarist** [comment]
Not sure why this was reported as rollup-plugin-babel issue, but with high confidence I believe it is a `rollup-plugin-commonjs` issue. I think there are known workarounds for this, but can't cite them from my head, so you'll gonna have to browse its issues etc.
