### ISSUE TITLE
An unexpected situation arose happen

### ISSUE THREAD

**Issue by jchbh-duplicate** [rollup/rollup-plugin-babel#183]
rollup not work for the setting following:
```
  "devDependencies": {
    "@babel/core": "^7.0.0-beta.35",
    "@babel/preset-env": "^7.0.0-beta.35",
    "@babel/plugin-external-helpers": "^7.0.0-beta.35",
    "babel-eslint": "^8.0.3",
    "eslint": "^4.13.1",
    "eslint-config-airbnb": "^16.1.0",
    "eslint-plugin-import": "^2.8.0",
    "eslint-plugin-jsx-a11y": "^6.0.3",
    "eslint-plugin-react": "^7.5.1",
    "micro-dev": "^2.1.1",
    "rollup": "^0.53.0",
    "rollup-plugin-babel": "^4.0.0-beta.0",
    "rollup-plugin-node-resolve": "^3.0.0",
    "rollup-watch": "^4.3.1"
  },
```
```
import babel from 'rollup-plugin-babel';
import resolve from 'rollup-plugin-node-resolve';

const pkg = require('./package.json');

const external = Object.keys(pkg.dependencies);

export default {
  input: 'index.js',
  external,
  output: {
    file: 'bundle.js',
    format: 'cjs',
  },
  plugins: [
    resolve(),
    babel({
      exclude: 'node_modules/**', // only transpile our source code
    }),
  ],
};
```

```
➜  node_modules/.bin/rollup -c

index.js → bundle.js...
[!] (babel plugin) Error: An unexpected situation arose. Please raise an issue at https://github.com/rollup/rollup-plugin-babel/issues. Thanks!
index.js
Error: An unexpected situation arose. Please raise an issue at https://github.com/rollup/rollup-plugin-babel/issues. Thanks!
    at error (rollup/dist/rollup.js:175:14)
    at Object.error (rollup/dist/rollup.js:18000:6)
    at promise.then.previous (rollup/dist/rollup.js:18009:32)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
    at Function.Module.runMain (module.js:703:11)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:618:3

``

**Comment by sebinsua** [comment]
I had this issue until I removed `"plugins": ["@babel/plugin-external-helpers"]` from my `.babelrc`. I'll try to find out why this is happening...

**Comment by zp1996** [comment]
```
  "presets": [
    [
      "@babel/preset-env", {
      "modules": false,
      "targets": {
        "node": "7.9",
      }
    }]
  ]
```

try this, i think it will be resolved.

**Comment by Andarist** [comment]
@jchbh-duplicate did u resolve ur issue? or is this still a problem for u?

**Comment by kopax** [comment]
I have same issue

**Comment by Andarist** [comment]
Please provide a repro case on which I could look and narrow it down. Without it there is nothing I can do to help you guys.

If you create one please open a new issue.

**Comment by DrSensor** [comment]
Probably this is because of incompatibility between babel 7/beta and rollup.
For anyone who stumbles this issue, try to use babel 6/stable version and see if it works 🙂
