### ISSUE TITLE
Error when using external-helpers with babel 7

### ISSUE THREAD

**Issue by giuvincenzi** [rollup/rollup-plugin-babel#230]
npm config
```
{
    "scripts": {
        "build": "rollup -c -i src/index.js -o lib/index.js"
    },
    "devDependencies": {
        "@babel/cli": "^7.0.0-beta.52",
        "@babel/core": "^7.0.0-beta.52",
        "@babel/plugin-external-helpers": "^7.0.0-beta.52",
        "@babel/polyfill": "^7.0.0-beta.52",
        "@babel/preset-env": "^7.0.0-beta.52",
        "rollup": "^0.62.0",
        "rollup-plugin-babel": "^4.0.0-beta.7",
        "rollup-plugin-json": "^3.0.0"
    }
}
```
rollup
```js
{
  external: [
    ...Object.keys(pkg.dependencies || {})
  ],
  plugins: [
    json(),
    babel({
      plugins: ['@babel/plugin-external-helpers']
    })
  ],
  output: {
    format: 'cjs',
    sourcemap: true
  }
}
```

```
$ npm run build
```

output
```shell
src/index.js → lib/index.js...
[!] (babel plugin) Error: An unexpected situation arose. Please raise an issue at https://github.com/rollup/rollup-plugin-babel/issues. Thanks!
src/index.js
Error: An unexpected situation arose. Please raise an issue at https://github.com/rollup/rollup-plugin-babel/issues. Thanks!
    at error (/home/node/app/node_modules/rollup/dist/rollup.js:3356:15)
    at Object.error (/home/node/app/node_modules/rollup/dist/rollup.js:20455:13)
    at /home/node/app/node_modules/rollup-plugin-babel/dist/rollup-plugin-babel.cjs.js:72:9
    at Object.transform$1 (/home/node/app/node_modules/rollup-plugin-babel/dist/rollup-plugin-babel.cjs.js:150:18)
    at /home/node/app/node_modules/rollup/dist/rollup.js:20478:41
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
```

**Comment by Andarist** [comment]
Could u share a repository with the issue reproduced in it?

Either way you don't have to use `'@babel/plugin-external-helpers'` with latest rollup-plugin-babel@beta - this optimization is done automatically for u.

I'd like to improve the error message if needed, but not sure what happened for you.

**Comment by giuvincenzi** [comment]
Ok thanks.

In the attachmen there's the project you asked for. 
I used node 8.9.0.

[rollup-plugin-babel-issues_230.zip](https://github.com/rollup/rollup-plugin-babel/files/2187559/rollup-plugin-babel-issues_230.zip)

```
$ npm install && npm run build
```
