### ISSUE TITLE
Cannot find module '@babel/core'

### ISSUE THREAD

**Issue by brytorres** [rollup/rollup-plugin-babel#251]
I'm new to rollup and was trying to get it to work with babel using https://rollupjs.org/guide/en#babel.
I ran `npm i -D rollup-plugin-babel`, `npm i -D babel-preset-env babel-plugin-external-helpers`,
and also added babel to the `rollup.config.js` file. Also created the `.babelrc` file as per the guide. 

I noticed the following warning when running those npm install commands:

```shell
npm WARN rollup-plugin-babel@4.0.3 requires a peer of @babel/core@7 || ^7.0.0-rc.2 but none is installed. You must install peer dependencies yourself.
```

When I run `npm run build` I get the following error:

```shell
[!] Error: Cannot find module '@babel/core'
Error: Cannot find module '@babel/core'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/create/dev/jsPlayground/node_modules/rollup-plugin-babel/dist/rollup-plugin-babel.cjs.js:4:12)
    at Module._compile (module.js:652:30)
    at Module._extensions..js (module.js:663:10)
    at Object.require.extensions..js (/usr/local/lib/node_modules/rollup/bin/rollup:1227:17)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
```
So I installed @babel/core, and ran `npm run build` again and got this:

```shel
[!] (babel plugin) Error: Babel 7.0.0-beta.56 has dropped support for the 'helpersNamespace' utility.If you are using @babel/plugin-external-helpers you will need to use a newer version than the one you currently have installed. If you have your own implementation, you'll want to explore using 'helperGenerator' alongside 'file.availableHelper()'.
```
After doing some research I found `babel-upgrade` and figured I'd give it a shot. `npm run build` worked after doing running `babel-upgrade --write` but returns the following log:

```shell
(!) babel plugin: Using "external-helpers" plugin with rollup-plugin-babel is deprecated, as it now automatically deduplicates your Babel helpers.
assets/js/src/main.js
(!) Unresolved dependencies
https://github.com/rollup/rollup/wiki/Troubleshooting#treating-module-as-external-dependency
(!) Missing global variable name
Use output.globals to specify browser global variable names corresponding to external modules
the-answer (guessing 'answer')
```
So the build works now, but it seemed to require some further changes.  I tried doing the babel setup from the beginning again but without `babel-plugin-external-helpers` and removing  `"plugins": ["@babel/plugin-external-helpers"]` from `.babelrc` but that gives this:

```shell
[!] (babel plugin) Error: Cannot find module '@babel/preset-env' from '/Users/create/dev/jsPlayground/assets/js/src'
```

Installing @babel/preset-env seems to help only showing this log when I run the build:

```shell
assets/js/src/main.js → assets/js/bundle.js...
(!) Missing global variable name
Use output.globals to specify browser global variable names corresponding to external modules
the-answer (guessing 'answer')
created assets/js/bundle.js in 500ms
```
----------
Here's my `main.js`, `package.json` and `rollup.config.js`:

```javascript
// main.js
import answer from 'the-answer'

export default () => {
    console.log('the answer is ' + answer)
}
```

package.json
```json
{
  "name": "jsPlayground",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "scripts": {
    "build": "rollup -c"
  },
  "dependencies": {
    "babel-preset-env": "^1.7.0",
    "the-answer": "^1.0.0"
  },
  "devDependencies": {
    "@babel/core": "^7.0.1",
    "@babel/preset-env": "^7.0.0",
    "rollup-plugin-babel": "^4.0.3"
  }
}
```

```javascript
// rollup.config.js
import babel from 'rollup-plugin-babel';

export default {
    input: 'assets/js/src/main.js',
    output: {
        file: 'assets/js/bundle.js',
        format: 'umd',
        name: 'main'
    },
    plugins: [
        babel({
            exclude: 'node_modules/**'
        })
    ]
};
```

**Comment by Andarist** [comment]
The turorial in rollup docs is outdated (for babel@6), and newest `rollup-plugin-babel` is compatible with babel@7- that's why you had to go through all of those hoops (upgrading from 6 to 7).

You got it working though (congrats!) and I'm not sure what's the question now. Could you precise it for me?

**Comment by Himself65** [comment]
@Andarist  have any Babel7 config example？

**Comment by Himself65** [comment]
@Andarist thanks

**Comment by SumNeuron** [comment]
I'm facing the same issue :/

**Comment by darran-kelinske-fivestars** [comment]
I am new to javascript and have the following issue - how did you all fix it?

```
 FAIL  src/redux/wallet/__tests__/reducer.test.ts
  ● Test suite failed to run

    /Users/fivestars.user/source/fivestars/consumer-mobile/node_modules/react-native/jest/setup.js: Babel 7.0.0-beta.56 has dropped support for the 'helpersNamespace' utility.If you are using @babel/plugin-external-helpers you will need to use a newer version than the one you currently have installed. If you have your own implementation, you'll want to explore using 'helperGenerator' alongside 'file.availableHelper()'.

      at File.set (node_modules/@babel/core/lib/transformation/file/file.js:127:13)
      at PluginPass.pre (node_modules/babel-plugin-external-helpers/lib/index.js:10:12)
      at transformFile (node_modules/@babel/core/lib/transformation/index.js:109:27)
      at runSync (node_modules/@babel/core/lib/transformation/index.js:48:5)
      at transformSync (node_modules/@babel/core/lib/transform.js:43:38)
      at Object.transform (node_modules/metro/src/reactNativeTransformer.js:163:5)
      at Object.process (node_modules/react-native/jest/preprocessor.js:51:31)
```

**Comment by FANZHETWO** [comment]
Why hasn't this problem been solved

**Comment by ClassicOldSong** [comment]
Installing using yarn could probably get this kind of error temporary solved but yarn could probably cause more issues so I'm don't think it as a good solution. This probably not an issue by this plugin but rollup or npm.
