### ISSUE TITLE
Error when babel-minify topLevel mangle and dynamic import

### ISSUE THREAD

**Issue by sansSpoon** [rollup/rollup-plugin-babel#272]
Similar to #268. I've been playing around with the rollup-starter-code-splitting project and babel 7.1 with babel minify and came across this error when trying to turn on top level mangling with dynamic imports:

```
[!] (babel plugin) Error: An unexpected situation arose. Please raise an issue at https://github.com/rollup/rollup-plugin-babel/issues. Thanks!
src/main-a.js
Error: An unexpected situation arose. Please raise an issue at https://github.com/rollup/rollup-plugin-babel/issues. Thanks!
    at error (/js-dynamic-import/node_modules/rollup/dist/rollup.js:3460:30)
    at Object.error (/js-dynamic-import/node_modules/rollup/dist/rollup.js:21252:17)
    at /js-dynamic-import/node_modules/rollup-plugin-babel/dist/rollup-plugin-babel.cjs.js:72:9
    at Object.transform$1 (/js-dynamic-import/node_modules/rollup-plugin-babel/dist/rollup-plugin-babel.cjs.js:174:18)
    at /js-dynamic-import/node_modules/rollup/dist/rollup.js:20963:25
    at internalTickCallback (internal/process/next_tick.js:77:7)
    at process._tickCallback (internal/process/next_tick.js:47:5)
    at Function.Module.runMain (internal/modules/cjs/loader.js:763:11)
    at startup (internal/bootstrap/node.js:303:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:872:3)
```

I get why this is happening; babel-minify can't mangle the function without also mangling the filename. Would this even be feasible? Is it something that should live with rollup or Babel-minify?

rollup config
```
import babel from 'rollup-plugin-babel';
export default [
  // ES module version, for modern browsers
  {
    input: ['src/main-a.js', 'src/main-b.js'],
    output: {
      dir: 'public/module',
      format: 'es',
      sourcemap: true
    },
    experimentalCodeSplitting: true,
    experimentalDynamicImport: true,
    plugins: [
      babel({
        exclude: 'node_modules/**',
      }),
    ]
  },

  // SystemJS version, for older browsers
  {
    input: ['src/main-a.js', 'src/main-b.js'],
    output: {
      dir: 'public/nomodule',
      format: 'system',
      sourcemap: true
    },
    experimentalCodeSplitting: true,
    experimentalDynamicImport: true
  }
];
```
babel config
```
module.exports = function (api) {
  const isProd = api.cache.invalidate(() => process.env.NODE_ENV === "production");
  const presets = [
    ["@babel/env", {
      "modules": false
    }],
  ];
  if(process.env.NODE_ENV === 'production') {
    presets.push(["minify", {
      "mangle": {
        "topLevel": true, // turn this off and minification is OK
      },
    }])
  }
  const plugins = [
    ["@babel/plugin-syntax-dynamic-import"],
  ];
  return {
    presets,
    plugins
  };
}
```

**Comment by sansSpoon** [comment]
fixed using: https://github.com/Comandeer/rollup-plugin-babel-minify
