### ISSUE TITLE
helpers(...).minVersion is not a function

### ISSUE THREAD

**Issue by Himself65** [rollup/rollup-plugin-babel#276]
- Rollup Version:  0.67.4
- Operating System (or Browser): Windows 10 1803
- Node Version: v11.2.0

### How Do We Reproduce?

1. clone https://github.com/Himself65/kuen/tree/bug
2.
> yarn
> lerna run build --scope=@kuen/loader

### Expected Behavior

```
$ rimraf dist && cross-env NODE_ENV=production rollup -c
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

lerna ERR! yarn run build stderr:

src/index.js → dist/kuen.cjs.js, dist/kuen.esm.js...
[!] (babel plugin) TypeError: helpers(...).minVersion is not a function
src\index.js
TypeError: helpers(...).minVersion is not a function
    at File.availableHelper (C:\Users\76128\Desktop\Himself65\kuen\node_modules\@babel\core\lib\transformation\file\file.js:180:30)
    at file.set.name (C:\Users\76128\Desktop\Himself65\kuen\node_modules\@babel\plugin-external-helpers\lib\index.js:45:43)
    at File.addHelper (C:\Users\76128\Desktop\Himself65\kuen\node_modules\@babel\core\lib\transformation\file\file.js:197:19)
    at PluginPass.ClassDeclaration (C:\Users\76128\Desktop\Himself65\kuen\node_modules\rollup-plugin-babel\src\preflightCheck.js:22:
33)
    at newFn (C:\Users\76128\Desktop\Himself65\kuen\node_modules\@babel\core\node_modules\@babel\traverse\lib\visitors.js:237:21)
    at NodePath._call (C:\Users\76128\Desktop\Himself65\kuen\node_modules\@babel\core\node_modules\@babel\traverse\lib\path\context.
js:65:20)
    at NodePath.call (C:\Users\76128\Desktop\Himself65\kuen\node_modules\@babel\core\node_modules\@babel\traverse\lib\path\context.j
s:40:17)
    at NodePath.visit (C:\Users\76128\Desktop\Himself65\kuen\node_modules\@babel\core\node_modules\@babel\traverse\lib\path\context.
js:100:12)
    at TraversalContext.visitQueue (C:\Users\76128\Desktop\Himself65\kuen\node_modules\@babel\core\node_modules\@babel\traverse\lib\
context.js:142:16)
    at TraversalContext.visitMultiple (C:\Users\76128\Desktop\Himself65\kuen\node_modules\@babel\core\node_modules\@babel\traverse\l
ib\context.js:97:17)

error Command failed with exit code 1.
```

### Actual Behavior

success build.

**Comment by loganfsmyth** [comment]
Running your demo produces a different error for me:
```
$ $(npm bin)/lerna run build --scope=@kuen/loader                                                     
lerna notice cli v3.6.0
lerna info filter [ '@kuen/loader' ]
lerna info Executing command in 1 package: "yarn run build"
lerna ERR! yarn run build exited 1 in '@kuen/loader'
lerna ERR! yarn run build stdout:
yarn run v1.10.1
$ rimraf dist && cross-env NODE_ENV=production rollup -c
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

lerna ERR! yarn run build stderr:

src/index.js → dist/kuen.cjs.js, dist/kuen.esm.js...
(!) babel plugin: Using "external-helpers" plugin with rollup-plugin-babel is deprecated, as it now automatically deduplicates your Babel helpers.
src/index.js
[!] Error: 'default' is not exported by ../../node_modules/axios/index.js
https://rollupjs.org/guide/en#error-name-is-not-exported-by-module-
src/utils/index.js (1:7)
1: import axios from 'axios'
          ^
2: 
3: export function get (url, data, ...conf) {
Error: 'default' is not exported by ../../node_modules/axios/index.js
    at error (/private/tmp/kuen/node_modules/rollup/dist/rollup.js:3460:30)
    at Module.error (/private/tmp/kuen/node_modules/rollup/dist/rollup.js:13349:9)
    at handleMissingExport (/private/tmp/kuen/node_modules/rollup/dist/rollup.js:13039:21)
    at Module.traceVariable (/private/tmp/kuen/node_modules/rollup/dist/rollup.js:13453:17)
    at ModuleScope.findVariable (/private/tmp/kuen/node_modules/rollup/dist/rollup.js:12726:29)
    at FunctionScope.Scope.findVariable (/private/tmp/kuen/node_modules/rollup/dist/rollup.js:4022:68)
    at Scope.findVariable (/private/tmp/kuen/node_modules/rollup/dist/rollup.js:4022:68)
    at MemberExpression$$1.bind (/private/tmp/kuen/node_modules/rollup/dist/rollup.js:11244:50)
    at CallExpression.NodeBase.bind (/private/tmp/kuen/node_modules/rollup/dist/rollup.js:9183:23)
    at CallExpression.bind (/private/tmp/kuen/node_modules/rollup/dist/rollup.js:10224:31)

error Command failed with exit code 1.

lerna ERR! yarn run build exited 1 in '@kuen/loader'
```

**Comment by Himself65** [comment]
@loganfsmyth 

my `yarn` version are `v1.12.3`

[![FsTs9P.md.png](https://s1.ax1x.com/2018/12/22/FsTs9P.md.png)](https://imgchr.com/i/FsTs9P)

**Comment by Andarist** [comment]
Have you fixed your problem? Once I change:
```js
import axios from 'axios'
```
to
```js
import * as axios from 'axios'
```
it build fine for me:
```
> lerna run build --scope=@kuen/loader

info cli using local version of lerna
lerna notice cli v3.6.0
lerna info filter [ '@kuen/loader' ]
lerna info Executing command in 1 package: "yarn run build"
lerna info run Ran npm script 'build' in '@kuen/loader' in 3.6s:
yarn run v1.10.1
$ rimraf dist && cross-env NODE_ENV=production rollup -c
Done in 3.37s.
lerna success run Ran npm script 'build' in 1 package in 3.6s:
lerna success - @kuen/loader
```

**Comment by Himself65** [comment]
@loganfsmyth  @Andarist 

I fixed this bug by following your advice.

And the reason that my pc displayed `[!] (babel plugin) TypeError: helpers(...).minVersion is not a function` may be caused by the wrong `node_modules` folder contents.

After I remove `node_modules` and `yarn.lock` then `yarn install`, finally the problem disappear.

Thank you very much for your help.
