### ISSUE TITLE
Plugin/Preset files are not allowed to export objects, only functions

### ISSUE THREAD

**Issue by priley86** [rollup/rollup-plugin-babel#291]
Hi - I am attempting to use this to add UMD support for our monorepo.

Getting the following with my Babel 7 project:
```
| => yarn build:umd
yarn run v1.12.3
$ cross-env BABEL_ENV=production:umd rollup -c scripts/rollup.config.js

./src/index.ts → dist/umd/@patternfly/react-core.development.js...
[!] (babel plugin) Error: Plugin/Preset files are not allowed to export objects, only functions. In /Users/priley/GitHub/patternfly-react/node_modules/babel-preset-react/lib/index.js
src/styles/gutters.js
Error: Plugin/Preset files are not allowed to export objects, only functions. In /Users/priley/GitHub/patternfly-react/node_modules/babel-preset-react/lib/index.js
    at createDescriptor (/Users/priley/GitHub/patternfly-react/node_modules/@babel/core/lib/config/config-descriptors.js:178:11)
    at items.map (/Users/priley/GitHub/patternfly-react/node_modules/@babel/core/lib/config/config-descriptors.js:109:50)
    at Array.map (<anonymous>)
    at createDescriptors (/Users/priley/GitHub/patternfly-react/node_modules/@babel/core/lib/config/config-descriptors.js:109:29)
    at createPresetDescriptors (/Users/priley/GitHub/patternfly-react/node_modules/@babel/core/lib/config/config-descriptors.js:101:10)
    at presets (/Users/priley/GitHub/patternfly-react/node_modules/@babel/core/lib/config/config-descriptors.js:47:19)
    at mergeChainOpts (/Users/priley/GitHub/patternfly-react/node_modules/@babel/core/lib/config/config-chain.js:320:26)
    at /Users/priley/GitHub/patternfly-react/node_modules/@babel/core/lib/config/config-chain.js:283:7
    at buildRootChain (/Users/priley/GitHub/patternfly-react/node_modules/@babel/core/lib/config/config-chain.js:90:20)
    at loadPrivatePartialConfig (/Users/priley/GitHub/patternfly-react/node_modules/@babel/core/lib/config/partial.js:85:55)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Here is the steps to reproduce:
```
git clone https://github.com/priley86/patternfly-react.git
git fetch origin umd-support:umd-support
git checkout umd-support
cd patternfly-react
yarn install
yarn build
cd packages/patternfly-4/react-core
yarn build:umd
```

I verified that removing the plugin removes the error (so have isolated it to this dependency). Can you please look at the rollup and babel js configs?
https://github.com/priley86/patternfly-react/blob/umd-support/packages/patternfly-4/react-core/scripts/rollup.config.js
https://github.com/priley86/patternfly-react/blob/umd-support/packages/patternfly-4/react-core/.babelrc.js

`build:umd` is here:
https://github.com/priley86/patternfly-react/blob/umd-support/packages/patternfly-4/react-core/package.json#L46

**Comment by Andarist** [comment]
I **guess** that `configFile` doesnt accept babelrc format (it's supposed to accept `babel.config.js` files).

I would try with such options:
```js
const babelOptions = Object.assign(
  {
    exclude: /node_modules/,
    babelrc: false,
  },
  require('../.babelrc.js'),
);
```

**Comment by priley86** [comment]
thanks! this resolved the issue.
