### ISSUE TITLE
throws Unexpected token for babel.config.js

### ISSUE THREAD

**Issue by brendonco** [rollup/rollup-plugin-babel#310]
package.json

```
"babel-cli": "^6.26.0",
    "babel-core": "^6.26.3",
    "babel-eslint": "^10.0.1",
    "babel-jest": "^23.6.0",
    "babel-loader": "^7.1.4",
    "babel-plugin-external-helpers": "^6.22.0",
    "babel-plugin-styled-components": "^1.10.0",
    "babel-plugin-syntax-dynamic-import": "^6.18.0",
    "babel-plugin-transform-object-assign": "^6.22.0",
    "babel-plugin-transform-object-rest-spread": "^6.26.0",
    "babel-polyfill": "^6.26.0",
    "babel-preset-env": "^1.7.0",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-es2017": "^6.24.1",
    "babel-preset-react": "^6.24.1",
    "bundle-loader": "^0.5.6",
    "clean-webpack-plugin": "^0.1.19",
    "css-loader": "^0.28.11",
    "enzyme": "^3.3.0",
    "enzyme-adapter-react-16": "^1.1.1",
    "eslint": "^4.19.1",
    "eslint-config-airbnb": "^16.1.0",
    "eslint-config-airbnb-base": "^12.1.0",
    "eslint-config-prettier": "^2.9.0",
    "eslint-import-resolver-webpack": "^0.10.0",
    "eslint-loader": "^2.0.0",
    "eslint-plugin-import": "^2.12.0",
    "eslint-plugin-jest": "^22.5.1",
    "eslint-plugin-jsx-a11y": "^6.0.3",
    "eslint-plugin-prettier": "^2.6.0",
    "eslint-plugin-react": "^7.13.0",
    "eslint_d": "^7.3.0",
    "file-loader": "^1.1.11",
    "html-webpack-plugin": "^3.2.0",
    "isparta": "^4.0.0",
    "jest": "^23.1.0",
    "jest-dom": "^3.2.2",
    "jest-junit": "^5.0.0",
    "jest-styled-components": "^6.3.1",
    "node-sass": "^4.9.0",
    "prettier": "^1.13.5",
    "react-test-renderer": "^16.4.0",
    "rollup": "^1.12.3",
    "rollup-plugin-babel": "^3.0.7",
    "rollup-plugin-node-resolve": "^5.0.0",
    "sass-loader": "^7.0.3",
    "style-loader": "^0.21.0",
    "stylelint": "^9.4.0",
    "stylelint-config-recommended": "^2.1.0",
    "stylelint-config-styled-components": "^0.1.1",
    "stylelint-custom-processor-loader": "^0.5.0",
    "stylelint-processor-styled-components": "^1.3.2",
```

babel.config.js

```
{
  "presets": [
    "env",
    "react",
    "es2015",
    "es2017"
  ],
  "plugins": [
    "external-helpers",
    "transform-object-assign",
    "transform-object-rest-spread",
    "syntax-dynamic-import",
    "react-loadable/babel",
    ["babel-plugin-styled-components", {
      "displayName": false,
      "pure": true
    }]
  ],
  "env": {
    "test": {
      "plugins": [
        "istanbul"
      ]
    }
  }
}
```

error:

```
 "presets": [
           ^

SyntaxError: Unexpected token :
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Module._extensions..js (module.js:663:10)
    at Object.require.extensions..js (AppData\Roaming\npm\node_modules\rollup\bin\rollup:1273:17)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
```

**Comment by loganfsmyth** [comment]
Since it is a JS file, you need to assign the config into the module export.

**Comment by Andarist** [comment]
Also babel.config.js is only supported since babel@7 and looking at your pasted in dependencies you are still using babel@6.
