### ISSUE TITLE
Vue + Babel: "Unexpected Situation Arose"

### ISSUE THREAD

**Issue by subdavis** [rollup/rollup-plugin-babel#315]
#302 appears to be similar to what I am experiencing, but the patron of that issue didn't really share how it was resolved.

## Steps to reproduce:

1. Clone the `rollup` branch of https://github.com/girder/girder_web_components/tree/rollup
2. `yarn`
3. `yarn rollup`

Please note that I am attempting to convert a large webpack project to rollup, so I don't expect that, if this issue is fixed, the build will succeed.  It's a slog.

I've tried switching node versions with `n`.  Nothing I have in the 8-12 range made a difference.

## Important files

```js

import vue from 'rollup-plugin-vue';
import replace from 'rollup-plugin-replace';
import resolve from 'rollup-plugin-node-resolve';
import babel from 'rollup-plugin-babel';
import scss from 'rollup-plugin-scss';
import stylus from 'rollup-plugin-stylus-compiler';
import commonjs from 'rollup-plugin-commonjs';
// import postcss from 'rollup-plugin-postcss';

const plugins = [
  stylus(),
  scss(),
  commonjs(),
  vue({ css: false }),
  replace({
    'process.env.NODE_ENV': JSON.stringify('production')
  }),
  resolve(),
  babel({
    exclude: 'node_modules/**',
  }),
];

const config = {
  input: 'src/index.js',
  output: {
    file: 'dist/gwc.js',
    format: 'esm',
    sourcemap: false,
  },
  plugins,
};

export default config;

```

Dependencies:
```js
  "dependencies": {
    "@mdi/font": "^3.5.95",
    "axios": "^0.18.0",
    "js-cookie": "^2.2.0",
    "markdown-it": "^8.4.2",
    "moment": "^2.24.0",
    "qs": "^6.5.2",
    "vue": "^2.5.21",
    "vue-async-computed": "^3.4.1",
    "vue-cli-plugin-vuetify": "^0.5.0",
    "vuetify": "^1.3.15",
    "vuetify-loader": "^1.2.1"
  },
  "devDependencies": {
    "@babel/core": "^7.5.4",
    "@vue/cli-plugin-babel": "^3.0.0",
    "@vue/cli-plugin-eslint": "^3.0.0",
    "@vue/cli-plugin-unit-jest": "^3.0.3",
    "@vue/cli-service": "^3.0.0",
    "@vue/eslint-config-airbnb": "^3.0.0",
    "@vue/test-utils": "^1.0.0-beta.20",
    "axios-mock-adapter": "^1.15.0",
    "babel-core": "7.0.0-bridge.0",
    "babel-jest": "^23.6.0",
    "node-sass": "^4.9.0",
    "pug-lint-vue": "^0.1.3",
    "rollup": "^1.16.7",
    "rollup-plugin-babel": "^4.3.3",
    "rollup-plugin-commonjs": "^10.0.1",
    "rollup-plugin-css-only": "^1.0.0",
    "rollup-plugin-node-resolve": "^5.2.0",
    "rollup-plugin-postcss": "^2.0.3",
    "rollup-plugin-replace": "^2.2.0",
    "rollup-plugin-scss": "^1.0.1",
    "rollup-plugin-stylus-compiler": "^1.0.1",
    "rollup-plugin-vue": "^5.0.1",
    "sass-loader": "^7.0.1",
    "stylelint": "^9.6.0",
    "stylelint-config-standard": "^18.2.0",
    "stylus": "^0.54.5",
    "stylus-loader": "^3.0.2",
    "vue-cli-plugin-pug": "^1.0.7",
    "vue-template-compiler": "^2.5.16",
}
```

## Full error

```

src/index.js → dist/gwc.js...                                                                                        
[!] (plugin babel) Error: An unexpected situation arose. Please raise an issue at https://github.com/rollup/rollup-plugin-babel/issues. Thanks!
src/index.js
Error: An unexpected situation arose. Please raise an issue at https://github.com/rollup/rollup-plugin-babel/issues. Thanks!
    at error (/home/brandon/kitware/github.com/girder_web_components/node_modules/rollup/dist/rollup.js:9402:30)
    at Object.error (/home/brandon/kitware/github.com/girder_web_components/node_modules/rollup/dist/rollup.js:15643:24)
    at Object.error (/home/brandon/kitware/github.com/girder_web_components/node_modules/rollup/dist/rollup.js:16083:38)
    at /home/brandon/kitware/github.com/girder_web_components/node_modules/rollup-plugin-babel/src/preflightCheck.js:58:9
    at /home/brandon/kitware/github.com/girder_web_components/node_modules/rollup-plugin-babel/src/index.js:95:22

error An unexpected error occurred: "Command failed.
Exit code: 1
Command: sh
Arguments: -c rollup -c
Directory: /home/brandon/kitware/github.com/girder_web_components
Output:
".
info If you think this is a bug, please open a bug report with the information provided in "/home/brandon/kitware/github.com/girder_web_components/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

## System

```
            .-/+oossssoo+/-.       
        `:+ssssssssssssssssss+:`           --------------------- 
      -+ssssssssssssssssssyyssss+-         OS: Ubuntu 18.04.2 LTS x86_64 
    .ossssssssssssssssssdMMMNysssso.       Host: XPS 13 9360 
   /ssssssssssshdmmNNmmyNMMMMhssssss/      Kernel: 4.15.0-52-generic 
  +ssssssssshmydMMMMMMMNddddyssssssss+     Uptime: 21 hours, 6 mins 
 /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Packages: 2788 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Shell: bash 4.4.19 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Resolution: 3200x1800 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   DE: i3-with-shmlog 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   WM: i3 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Theme: Breeze [GTK2/3] 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Icons: Breeze [GTK2/3] 
 /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/    Terminal: x-terminal-emul 
  +sssssssssdmydMMMMMMMMddddyssssssss+     CPU: Intel i7-7500U (4) @ 3.500GHz 
   /ssssssssssshdmNNNNmyNMMMMhssssss/      GPU: Intel HD Graphics 620 
    .ossssssssssssssssssdMMMNysssso.       Memory: 4502MiB / 7618MiB 
      -+sssssssssssssssssyyyssss+- 
        `:+ssssssssssssssssss+:`                                   
            .-/+oossssoo+/-. 

```

node 12.6.0 (and many others)
yarn 1.5.1

yarn error log attached.

[yarn-error.log](https://github.com/rollup/rollup-plugin-babel/files/3390420/yarn-error.log)

Thanks in advance.

**Comment by Andarist** [comment]
You have removed the branch containing a repro case so I can't quite take a look at this now. Going to close this issue as I'm not sure if you are still interested in this, bit if you are - then feel free to reopen with the repro case and I'll get back to you (and I promise it will be way sooner than the last time).
