### ISSUE TITLE
Rollup + babel basically incompatible with mocha + babel

### ISSUE THREAD

**Issue by callumacrae** [rollup/rollup-plugin-babel#42]
I wrote my tests using ES6 modules in mocha, running through Babel:

https://github.com/callumacrae/deity/blob/master/test/deity.spec.js

That means they need the transform-es2015-modules-commonjs plugin to work.

If I convert the imports in my tests to use `require(...).default` and load babel-register manually to load the transform-es2015-modules-commonjs plugin (which also doubles the start time of my tests), I get the following error:

```
/Users/callumacrae/Sites/deity/src/index.js:10
var _range2 = babelHelpers.interopRequireDefault(_range);
              ^
ReferenceError: babelHelpers is not defined
    at Object.<anonymous> (index.js:18:25)
    at Module._compile (module.js:460:26)
    at loader (/Users/callumacrae/Sites/deity/node_modules/babel-register/lib/node.js:128:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/callumacrae/Sites/deity/node_modules/babel-register/lib/node.js:138:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (core-generators.spec.js:7:15)
    at Module._compile (module.js:460:26)
    at loader (/Users/callumacrae/Sites/deity/node_modules/babel-register/lib/node.js:128:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/callumacrae/Sites/deity/node_modules/babel-register/lib/node.js:138:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /Users/callumacrae/Sites/deity/node_modules/mocha/lib/mocha.js:219:27
    at Array.forEach (native)
    at Mocha.loadFiles (/Users/callumacrae/Sites/deity/node_modules/mocha/lib/mocha.js:216:14)
    at Mocha.run (/Users/callumacrae/Sites/deity/node_modules/mocha/lib/mocha.js:468:10)
    at Object.<anonymous> (/Users/callumacrae/Sites/deity/node_modules/mocha/bin/_mocha:403:18)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

Here's what I tried: https://github.com/callumacrae/deity/commit/a24793ddf99df2f0371a01a5e7b5cfb2fb96c3c7

Is it actually possible to use babel with both rollup and mocha? I really like the idea of rollup, but I can't use it if it doesn't work in my existing setup! (also if this is something that could be done by a first time contributor, I'd be more than willing to have a go)

**Comment by Rich-Harris** [comment]
Just to go confusingly meta, rollup-plugin-babel is *itself* an example of using Rollup + Babel + Mocha. The project has a `.babelrc` file at the project root that looks like this:

```json
{
  "presets": [ "es2015" ]
}
```

Meanwhile `src/.babelrc` looks like this:

```json
{
  "presets": [ "es2015-rollup" ]
}
```

Running `npm test` [is equivalent to](https://github.com/rollup/rollup-plugin-babel/blob/master/package.json#L24-L30) `mocha --compilers js:babel-register`.

**The important thing here** is that the tests import the *built* module, not the source code. So there's no confusion over which config applies where. Personally I think that's better anyway, as it eliminates the potential for bugs in the build process to affect users of the library – we're all testing the same end product.

If you really did need to import source code into your tests (e.g. for unit testing functionality that wasn't exposed by the library) you should be able to do that by sticking with the `es2015` preset (or whatever combination of plugins you're using that includes the commonjs transformer) and preventing Rollup from seeing it with `babelrc: false`:

```js
// rollup.config.js
import babel from 'rollup-plugin-babel';

export default {
  entry: 'src/index.js',
  plugins: [
    babel({
      presets: [ 'es2015-rollup' ],
      babelrc: false
    })
  ],
  ...
};
```

**Comment by callumacrae** [comment]
I had no idea the babelrc option existed. My package is only exporting one function and there's quite a few being tested, so while I should probably still have functional tests for the built code, I think I'll go for the second approach for my unit tests.

Thank you!

**Comment by njpanderson** [comment]
Apologies for opening this but thought this might help people finding their way to their thread.

You don't technically need to use the `es2015-rollup` preset if you define something like the following in your rollup `plugins` array:

```
// rollup.config.js
babel({
	babelrc: false, // stops babel from using .babelrc files
	plugins: ['external-helpers'], // [1]
	presets: [
		'react', // (I'm using react in this example)
		['env', {
			'modules': false, // stop module conversion
			'targets': {
				'browsers': ['last 2 versions'] // whatever you want here
			}
		}],
	],
	exclude: [
		'node_modules/**'
	]
})
```

And then leave your root level .babelrc as something like the following, for the purposes of using Mocha or any instrumentation tools:

```
// .babelrc
{
  "presets": [
		"react",
		["env", {
			"targets": {
				"node": "current"
			}
		}]
  ]
}
```

This way, you can use the more recent `env` preset which I believe has deprecated a lot of the older ones. (https://babeljs.io/docs/plugins/preset-env/)

[1] external-helpers  - https://babeljs.io/docs/plugins/external-helpers/
