### ISSUE TITLE
2.5.0 breaks anything that uses typeof

### ISSUE THREAD

**Issue by chriso** [rollup/rollup-plugin-babel#59]
I see the following changes in my code when going from 2.4.0 to 2.5.0:

```javascript
      var typeof = typeof Symbol === "function" && typeof Symbol.iterator === "symbol" ? function (obj) {
        return typeof obj;
      } : function (obj) {
        return obj && typeof Symbol === "function" && obj.constructor === Symbol ? "symbol" : typeof obj;
      };
```

Previously it was this:

```javascript
      var babelHelpers = {};
      babelHelpers.typeof = typeof Symbol === "function" && typeof Symbol.iterator === "symbol" ? function (obj) {
        return typeof obj;
      } : function (obj) {
        return obj && typeof Symbol === "function" && obj.constructor === Symbol ? "symbol" : typeof obj;
      };
      babelHelpers;
```

Minifying the first chunk of code with uglify-js fails with an error, since `typeof` is a keyword:

```javascript
$ echo 'var typeof = 1' | ./node_modules/.bin/uglifyjs
Parse error at -:1,4
Name expected
Error
    at new JS_Parse_Error (eval at <anonymous> (/Users/chris/Documents/validator.js/node_modules/uglify-js/tools/node.js:24:4), <anonymous>:1526:18)
    at js_error (eval at <anonymous> (/Users/chris/Documents/validator.js/node_modules/uglify-js/tools/node.js:24:4), <anonymous>:1534:11)
    at croak (eval at <anonymous> (/Users/chris/Documents/validator.js/node_modules/uglify-js/tools/node.js:24:4), <anonymous>:2026:9)
    at as_symbol (eval at <anonymous> (/Users/chris/Documents/validator.js/node_modules/uglify-js/tools/node.js:24:4), <anonymous>:2664:27)
    at vardefs (eval at <anonymous> (/Users/chris/Documents/validator.js/node_modules/uglify-js/tools/node.js:24:4), <anonymous>:2432:25)
    at var_ (eval at <anonymous> (/Users/chris/Documents/validator.js/node_modules/uglify-js/tools/node.js:24:4), <anonymous>:2446:27)
    at eval (eval at <anonymous> (/Users/chris/Documents/validator.js/node_modules/uglify-js/tools/node.js:24:4), <anonymous>:2194:30)
    at eval (eval at <anonymous> (/Users/chris/Documents/validator.js/node_modules/uglify-js/tools/node.js:24:4), <anonymous>:2073:24)
    at eval (eval at <anonymous> (/Users/chris/Documents/validator.js/node_modules/uglify-js/tools/node.js:24:4), <anonymous>:2827:23)
    at Object.parse (eval at <anonymous> (/Users/chris/Documents/validator.js/node_modules/uglify-js/tools/node.js:24:4), <anonymous>:2837:7)
```

Node rejects it too:

```
$ echo 'var typeof = 1;' > typeof.js
$ node typeof.js 
/Users/chris/Documents/validator.js/typeof.js:1
(function (exports, require, module, __filename, __dirname) { var typeof = 1
                                                                  ^^^^^^
SyntaxError: Unexpected token typeof
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by chriso** [comment]
https://github.com/rollup/rollup-plugin-babel/commit/5722917c1d59f81bbc2f7985518bc177ebbccf5b appears to be the commit that made the change.

**Comment by chriso** [comment]
Here's the script I use to generate a version of validator.js for the browser: https://github.com/chriso/validator.js/blob/master/build-browser.js

**Comment by Rich-Harris** [comment]
Sorry about this – it's actually a bug in Rollup itself. Can you `npm i -D rollup@latest` and check that the issue doesn't persist? Thanks

Ref https://github.com/rollup/rollup-plugin-babel/issues/55

**Comment by chriso** [comment]
That works, thanks.
