### ISSUE TITLE
fails transform-runtime when using async functions

### ISSUE THREAD

**Issue by petamoriken** [rollup/rollup-plugin-babel#97]
input:
```javascript
(async function() {
  console.log("hoge");
})();
```

error:
```
node_modules/regenerator-runtime/runtime-module.js (5:267) The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten. See https://github.com/rollup/rollup/wiki/Troubleshooting#this-is-undefined for more information
The 'typeof' Babel helper is used more than once in your code. It's strongly recommended that you use the "external-helpers" plugin or the "es2015-rollup" preset. See https://github.com/rollup/rollup-plugin-babel#configuring-babel for more information
A module cannot import itself (/Users/Moriken/Sites/runtime-test/node_modules/babel-runtime/helpers/typeof.js)
Error: A module cannot import itself (/Users/Moriken/Sites/runtime-test/node_modules/babel-runtime/helpers/typeof.js)
    at /Users/Moriken/Sites/runtime-test/node_modules/rollup/src/Bundle.js:335:14
Type rollup --help for help, or visit https://github.com/rollup/rollup/wiki
```

rollup.config.js
```js
import babel from "rollup-plugin-babel";
import commonjs from "rollup-plugin-commonjs";
import nodeResolve from "rollup-plugin-node-resolve";

export default {
    entry:      "input.js",
    dest:       "output.js",
    plugins: [
        babel({
            runtimeHelpers: true
        }),
        commonjs(),
        nodeResolve()
    ]
}
```

.babelrc
```json
{
	"presets":	[
		["latest", {
			"es2015": {
				"modules": false
			}
		}],
		"stage-3"
	],
	"plugins":	[
		"transform-runtime"
	]
}
```

|modules|version|
|---|---|
|rollup|0.36.3|
|rollup-plugin-babel|2.6.1|
|rollup-plugin-commonjs|5.0.5|
|rollup-plugin-node-resolve|2.0.0|
|babel-core|6.18.0|
|babel-preset-latest|6.16.0|
|babel-preset-stage-3|6.17.0|
|babel-plugin-transform-runtime|6.15.0|
|babel-runtime|6.18.0|

**Comment by kennetpostigo** [comment]
I get this same problem. How do we go about fixing this? It works when node.env is set to development but fails when set to production for me. Why is this?

**Comment by kennetpostigo** [comment]
This is what my `rollup.config.js` looks like:
```js
import path from 'path';
import babel from 'rollup-plugin-babel';
import async from 'rollup-plugin-async';

var dest = 'dist/greed.js';
var destES = 'dist/greed.es.js';
if (process.env.NODE_ENV === 'production') {
	dest = 'dist/greed.min.js';
	destES = 'dist/greed.min.es.js';
}
export default {
	entry: 'src/greed.js',
	moduleName: 'Greed',
	targets: [
		{ dest: dest, format: 'umd' },
		{ dest: destES, format: 'es' },
	],
	plugins: [
		async(),
		babel({
			runtimeHelpers: true,
			babelrc: true,
			exclude: 'node_modules/**',
		})
	],
	external: [
    'whatwg-fetch',
		'babel-runtime/regenerator'
	],
	globals: {
    'whatwg-fetch': 'whatwg-fetch',
		'babel-runtime/regenerator': 'babel-runtime/regenerator',
	}
};
```

and the `.babelrc`:
```js
{
  "presets": [
    "es2015-rollup",
    "stage-1"
  ],
  "plugins": [
    ["transform-runtime", {
    "polyfill": false,
    "regenerator": true
    }]
  ],
  "env": {
    "production": {
      "presets": ["babili"],
      "comments": false,
      "minified": true,
      "compact": true
    }
  }
}
```
The odd things is that it will only work when the `process.env.NODE_ENV` is not set to production. When it is in production I get this error:
```js
> greed@0.1.0 build:production /Users/kennetpostigo/Projects/greed
> cross-env NODE_ENV=production rollup -c ./rollup.config.js

Error transforming /Users/kennetpostigo/Projects/greed/src/greed.js with 'babel' plugin: An unexpected situation arose. Please raise an issue at https://github.com/rollup/rollup-plugin-babel/issues
. Thanks!
Error: Error transforming /Users/kennetpostigo/Projects/greed/src/greed.js with 'babel' plugin: An unexpected situation arose. Please raise an issue at https://github.com/rollup/rollup-plugin-babel
/issues. Thanks!
    at preflightCheck (/Users/kennetpostigo/Projects/greed/node_modules/rollup-plugin-babel/dist/rollup-plugin-babel.cjs.js:50:10)
    at Object.transform$1 [as transform] (/Users/kennetpostigo/Projects/greed/node_modules/rollup-plugin-babel/dist/rollup-plugin-babel.cjs.js:104:18)
    at /Users/kennetpostigo/.nvm/versions/node/v7.0.0/lib/node_modules/rollup/src/utils/transform.js:19:35
    at process._tickCallback (internal/process/next_tick.js:103:7)
    at Module.runMain (module.js:609:11)
    at run (bootstrap_node.js:382:7)
    at startup (bootstrap_node.js:137:9)

    at bootstrap_node.js:497:3
Type rollup --help for help, or visit https://github.com/rollup/rollup/wiki
```

Hopefully this is enough information, but if you need any other information I would gladly provide it. I'm running the following babel and rollup versions:
```js
    // dev dependencies
    "babel-core": "6.18.2",
    "babel-plugin-transform-runtime": "6.15.0",
    "babel-preset-es2015-rollup": "1.2.0",
    "babel-preset-stage-1": "6.16.0",
    "babili": "0.0.8",
    "rollup": "0.36.3",
    "rollup-plugin-async": "1.1.0",
    "rollup-plugin-babel": "2.6.1",
    // dependencies
    "babel-runtime": "6.18.0"
```
with `nodev7.0.0`

**Comment by petamoriken** [comment]
the same content
https://github.com/babel/babel/issues/3711#issuecomment-255625766

**Comment by Rich-Harris** [comment]
Hi – sorry for the slow response. Am unable to reproduce this with the latest version (v3.0.0), can you see if it's still happening, or if we can close this issue (it may have been fixed)? Thanks

**Comment by Andarist** [comment]
Closing because original author has not provided a repro case that would allow finding the cause & fixing this.
